# Generated by Django 5.0 on 2023-12-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Qustion",
            new_name="Question",
        ),
    ]
